name: .NET Core CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: .NET on ${{ matrix.runs-on }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-latest, macos-14, ubuntu-latest, windows-latest]
        configuration: [Release, Debug]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4

      - name: Build
        run: dotnet publish DepotDumper/DepotDumper.csproj -c ${{ matrix.configuration }} -o artifacts /p:ContinuousIntegrationBuild=true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: matrix.configuration == 'Release' && matrix.runs-on == 'windows-latest'
        with:
          name: DepotDumper-framework
          path: artifacts
          if-no-files-found: error

      - name: Publish Windows-x64
        if: matrix.configuration == 'Release' && matrix.runs-on == 'windows-latest'
        run: dotnet publish DepotDumper/DepotDumper.csproj --configuration Release -p:PublishSingleFile=true -p:DebugType=embedded --self-contained --runtime win-x64 --output selfcontained-win-x64

      - name: Publish Windows-arm64
        if: matrix.configuration == 'Release' && matrix.runs-on == 'windows-latest'
        run: dotnet publish DepotDumper/DepotDumper.csproj --configuration Release -p:PublishSingleFile=true -p:DebugType=embedded --self-contained --runtime win-arm64 --output selfcontained-win-arm64

      - name: Publish Linux-x64
        if: matrix.configuration == 'Release' && matrix.runs-on == 'ubuntu-latest'
        run: dotnet publish DepotDumper/DepotDumper.csproj --configuration Release -p:PublishSingleFile=true -p:DebugType=embedded --self-contained --runtime linux-x64 --output selfcontained-linux-x64

      - name: Publish Linux-arm
        if: matrix.configuration == 'Release' && matrix.runs-on == 'ubuntu-latest'
        run: dotnet publish DepotDumper/DepotDumper.csproj --configuration Release -p:PublishSingleFile=true -p:DebugType=embedded --self-contained --runtime linux-arm --output selfcontained-linux-arm

      - name: Publish Linux-arm64
        if: matrix.configuration == 'Release' && matrix.runs-on == 'ubuntu-latest'
        run: dotnet publish DepotDumper/DepotDumper.csproj --configuration Release -p:PublishSingleFile=true -p:DebugType=embedded --self-contained --runtime linux-arm64 --output selfcontained-linux-arm64

      - name: Publish macOS-x64
        if: matrix.configuration == 'Release' && matrix.runs-on == 'macos-latest'
        run: dotnet publish DepotDumper/DepotDumper.csproj --configuration Release -p:PublishSingleFile=true -p:DebugType=embedded --self-contained --runtime osx-x64 --output selfcontained-osx-x64

      - name: Publish macOS-arm64
        if: matrix.configuration == 'Release' && matrix.runs-on == 'macos-14'
        run: dotnet publish DepotDumper/DepotDumper.csproj --configuration Release -p:PublishSingleFile=true -p:DebugType=embedded --self-contained --runtime osx-arm64 --output selfcontained-osx-arm64

      - name: Upload Windows-x64
        uses: actions/upload-artifact@v4
        if: matrix.configuration == 'Release' && matrix.runs-on == 'windows-latest'
        with:
          name: DepotDumper-windows-x64
          path: selfcontained-win-x64
          if-no-files-found: error

      - name: Upload Windows-arm64
        uses: actions/upload-artifact@v4
        if: matrix.configuration == 'Release' && matrix.runs-on == 'windows-latest'
        with:
          name: DepotDumper-windows-arm64
          path: selfcontained-win-arm64
          if-no-files-found: error

      - name: Upload Linux-x64
        uses: actions/upload-artifact@v4
        if: matrix.configuration == 'Release' && matrix.runs-on == 'ubuntu-latest'
        with:
          name: DepotDumper-linux-x64
          path: selfcontained-linux-x64
          if-no-files-found: error

      - name: Upload Linux-arm
        uses: actions/upload-artifact@v4
        if: matrix.configuration == 'Release' && matrix.runs-on == 'ubuntu-latest'
        with:
          name: DepotDumper-linux-arm
          path: selfcontained-linux-arm
          if-no-files-found: error

      - name: Upload Linux-arm64
        uses: actions/upload-artifact@v4
        if: matrix.configuration == 'Release' && matrix.runs-on == 'ubuntu-latest'
        with:
          name: DepotDumper-linux-arm64
          path: selfcontained-linux-arm64
          if-no-files-found: error

      - name: Upload macOS-x64
        uses: actions/upload-artifact@v4
        if: matrix.configuration == 'Release' && matrix.runs-on == 'macos-latest'
        with:
          name: DepotDumper-macos-x64
          path: selfcontained-osx-x64
          if-no-files-found: error

      - name: Upload macOS-arm64
        uses: actions/upload-artifact@v4
        if: matrix.configuration == 'Release' && matrix.runs-on == 'macos-14'
        with:
          name: DepotDumper-macos-arm64
          path: selfcontained-osx-arm64
          if-no-files-found: error
  create-release:
    name: Create release
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts/

      - name: Display downloaded artifacts
        run: find ./artifacts/
        
      - name: Create release files
        run: |
          set -eux
          mkdir release
          chmod +x ./artifacts/DepotDumper-linux-x64/DepotDumper
          chmod +x ./artifacts/DepotDumper-linux-arm/DepotDumper
          chmod +x ./artifacts/DepotDumper-linux-arm64/DepotDumper
          chmod +x ./artifacts/DepotDumper-macos-x64/DepotDumper
          chmod +x ./artifacts/DepotDumper-macos-arm64/DepotDumper
          zip -9j ./release/DepotDumper-framework.zip ./artifacts/DepotDumper-framework/*
          zip -9j ./release/DepotDumper-windows-x64.zip ./artifacts/DepotDumper-windows-x64/*
          zip -9j ./release/DepotDumper-windows-arm64.zip ./artifacts/DepotDumper-windows-arm64/*
          zip -9j ./release/DepotDumper-linux-x64.zip ./artifacts/DepotDumper-linux-x64/*
          zip -9j ./release/DepotDumper-linux-arm.zip ./artifacts/DepotDumper-linux-arm/*
          zip -9j ./release/DepotDumper-linux-arm64.zip ./artifacts/DepotDumper-linux-arm64/*
          zip -9j ./release/DepotDumper-macos-x64.zip ./artifacts/DepotDumper-macos-x64/*
          zip -9j ./release/DepotDumper-macos-arm64.zip ./artifacts/DepotDumper-macos-arm64/*
      
      - name: Display release files
        run: find ./release/

      - name: Create rolling release
        if: github.ref == 'refs/heads/main'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest rolling release"
          files: |
            ./release/DepotDumper-framework.zip
            ./release/DepotDumper-windows-x64.zip
            ./release/DepotDumper-windows-arm64.zip
            ./release/DepotDumper-linux-x64.zip
            ./release/DepotDumper-linux-arm.zip
            ./release/DepotDumper-linux-arm64.zip
            ./release/DepotDumper-macos-x64.zip
            ./release/DepotDumper-macos-arm64.zip
